%Patrick Riley
%11/6/19
%This is the final matlab project with the swimsuit datset

%% Import data from text file (Taken from the matlab import data functionality)
% Script for importing data from the following text file:
%
%    filename:  ./swimsuit.csv
%
% Auto-generated by MATLAB on 05-Nov-2019 14:14:06

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Year", "Month", "SearchInterest"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
swimsuit_searches = readtable("/swimsuit.csv", opts);
ss = readmatrix("/swimsuit.csv");

%% Clear temporary variables
clear opts

monthly_average = zeros(1, 12);
monthly_data = zeros(16,12);
for month = 1:12
    r = find(swimsuit_searches.Month == month);
    monthly_searches = swimsuit_searches(r,:);

    if length(monthly_searches.SearchInterest) == 16
        monthly_data(:,month) = monthly_searches.SearchInterest;
    else
        temp = monthly_searches.SearchInterest;
        while length(temp) < 16
            temp(length(temp) + 1) = 0;
        end
        monthly_data(:, month) = temp;
    end

    avg = mean(monthly_searches.SearchInterest);
    monthly_average(month) = avg;

end

%bar(monthly_average,.8);
boxplot(monthly_data);
xlabel("Month");
ylabel("Average Search Interest");
title("Average Monthly Interest for Term 'Swimsuit'");